project:
  type: website

website:
  title: "Shunsuke Murata - Research Group" # 
  # site-url: https://github.com/shunsukemurata
  page-navigation: false
  favicon: "logo/tohoku_univ/Toh_E_L_N_RGB.gif"
  google-analytics: "G-YP5LFKST0E"
  search: false 
  navbar:
    #background: "#3e1485" #  hex color
    background: "white" # transparent
    foreground: "#3e1485" ##f8f8f8
    logo: "logo/tohoku_univ/Toh_E_L_N_RGB.gif"
    right:
      #- icon: github
      #  href: https://github.com/shunsukemurata
      #  aria-label: Quarto GitHub
      - text: "EN"
        href: index.qmd
      - text: "JA"
        href: index_ja.qmd
        
  sidebar:
    - id: en
      style: "docked"
      contents:
        - text: "About us"
          href: index.qmd#about
        - text: "Member"
          href: index.qmd#member
        - text: "Join our team"
          href: index.qmd#hiring
        - text: "Publications"
          href: index.qmd#publications
        - text: "Funding"
          href: index.qmd#funding
    - id: ja
      style: "docked"
      contents:
        - text: "研究概要"
          href: index_ja.qmd#about
        - text: "メンバー"
          href: index_ja.qmd#member
        - text: "募集"
          href: index_ja.qmd#hiring
        - text: "研究業績"
          href: index_ja.qmd#publications
        - text: "研究費"
          href: index_ja.qmd#funding

format:
  html:
    theme:
      light: flatly
      # dark: darkly
    css: styles.css
    toc: false

editor: visual