project:
  type: website
  output-dir: _site

website:
  title: "Shunsuke Murata - Research Group"
  # site-url: https://shunsukemurata.github.io
  page-navigation: false
  favicon: "logo/tohoku_univ/Toh_E_L_N_RGB.gif"
  google-analytics: "G-NBK3WB71PM"
  search: falsegas
  navbar:
    background: "white"
    foreground: "#3e1485"
    logo: "logo/tohoku_univ/Toh_E_L_N_RGB.gif"
    right:
      - text: "EN"
        href: index.qmd
      - text: "JA"
        href: ja/index.qmd

  sidebar:
    - id: en
      style: "docked"
      contents:
        - text: "About us"
          href: index.qmd#about
        - text: "Member"
          href: index.qmd#member
        - text: "Join our team"
          href: index.qmd#join-our-team
        - text: "Publications"
          href: index.qmd#publications
        - text: "Funding"
          href: index.qmd#funding
    - id: ja
      style: "docked"
      contents:
        - text: "研究概要"
          href: ja/index.qmd#about
        - text: "メンバー"
          href: ja/index.qmd#member
        - text: "募集"
          href: ja/index.qmd#join-our-team
        - text: "研究業績"
          href: ja/index.qmd#publications
        - text: "研究費"
          href: ja/index.qmd#funding

format:
  html:
    theme:
      light: flatly
    css: styles.css
    toc: false

editor: visual